name: dart_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  dio: ^4.0.0
  flutter_screenutil: ^5.0.0+2 #屏幕适配
  provider: ^5.0.0
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.4
  json_annotation: ^4.0.0
  singleton: ^ 0.0.3-nullsafety  #单例
  fluttertoast: ^8.0.7
  flutter_spinkit: ^5.0.0
  flutter_sticky_header: ^0.6.0 #scrollerView

  flutter_swiper_null_safety : ^1.0.2
  flutter_staggered_grid_view: ^0.4.0  #瀑布流
  photo_view: ^0.12.0 # 图片预览

  logger: ^1.0.0
  flutter_easyrefresh: ^2.2.1
  connectivity: ^3.0.6
  flutter_marquee: ^2.0.1
  flutter_html: ^2.1.1
  flutter_custom_bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar

  cached_network_image: ^3.1.0
  barcode_widget: ^2.0.1
  geolocator: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/clickBack.png
    - assets/images/2.0x/clickBack.png
    - assets/images/3.0x/clickBack.png

    - assets/images/aboutUs.png
    - assets/images/2.0x/aboutUs.png
    - assets/images/3.0x/aboutUs.png

    - assets/images/lianxikefu.png
    - assets/images/2.0x/lianxikefu.png
    - assets/images/3.0x/lianxikefu.png

    - assets/images/shezhi.png
    - assets/images/2.0x/shezhi.png
    - assets/images/3.0x/shezhi.png

    - assets/images/shouhuodizhi.png
    - assets/images/2.0x/shouhuodizhi.png
    - assets/images/3.0x/shouhuodizhi.png

    - assets/images/wodetanwei.png
    - assets/images/2.0x/wodetanwei.png
    - assets/images/3.0x/wodetanwei.png

    - assets/images/wodeyinhangka.png
    - assets/images/2.0x/wodeyinhangka.png
    - assets/images/3.0x/wodeyinhangka.png

    - assets/images/seeIcon.png
    - assets/images/2.0x/seeIcon.png
    - assets/images/3.0x/seeIcon.png

    - assets/images/login_icon_guanbi.png
    - assets/images/2.0x/login_icon_guanbi.png
    - assets/images/3.0x/login_icon_guanbi.png

    - assets/images/login_pic.png
    - assets/images/2.0x/login_pic.png
    - assets/images/3.0x/login_pic.png

    - assets/images/noShopCart.png
    - assets/images/2.0x/noShopCart.png
    - assets/images/3.0x/noShopCart.png

    - assets/images/noNet.png
    - assets/images/2.0x/noNet.png
    - assets/images/3.0x/noNet.png

    - assets/images/avater_icon.png
    - assets/images/2.0x/avater_icon.png
    - assets/images/3.0x/avater_icon.png

    - assets/images/mine_icon_mine_onclick.png
    - assets/images/2.0x/mine_icon_mine_onclick.png
    - assets/images/3.0x/mine_icon_mine_onclick.png

    - assets/images/mine_icon_mine_click.png
    - assets/images/2.0x/mine_icon_mine_click.png
    - assets/images/3.0x/mine_icon_mine_click.png

    - assets/images/mine_icon_store_onclick.png
    - assets/images/2.0x/mine_icon_store_onclick.png
    - assets/images/3.0x/mine_icon_store_onclick.png

    - assets/images/mine_icon_store_click.png
    - assets/images/2.0x/mine_icon_store_click.png
    - assets/images/3.0x/mine_icon_store_click.png

    - assets/images/icon_shoppingcar_click.png
    - assets/images/2.0x/icon_shoppingcar_click.png
    - assets/images/3.0x/icon_shoppingcar_click.png

    - assets/images/icon_shoppingcar_onclick.png
    - assets/images/2.0x/icon_shoppingcar_onclick.png
    - assets/images/3.0x/icon_shoppingcar_onclick.png

    - assets/images/designCourse.png
    - assets/images/2.0x/designCourse.png
    - assets/images/3.0x/designCourse.png

    - assets/images/designReport.png
    - assets/images/2.0x/designReport.png
    - assets/images/3.0x/designReport.png

    - assets/images/findDesigner.png
    - assets/images/2.0x/findDesigner.png
    - assets/images/3.0x/findDesigner.png

    - assets/images/fastReport.png
    - assets/images/2.0x/fastReport.png
    - assets/images/3.0x/fastReport.png

    - assets/images/privateSchool.png
    - assets/images/2.0x/privateSchool.png
    - assets/images/3.0x/privateSchool.png

    - assets/images/planningCase.png
    - assets/images/2.0x/planningCase.png
    - assets/images/3.0x/planningCase.png

    - assets/images/ylz_arrow_right.png
    - assets/images/2.0x/ylz_arrow_right.png
    - assets/images/3.0x/ylz_arrow_right.png

    - assets/images/home_icon_tax_shape.png
    - assets/images/2.0x/home_icon_tax_shape.png
    - assets/images/3.0x/home_icon_tax_shape.png

    - assets/images/chs_logo_hsa.png
    - assets/images/2.0x/chs_logo_hsa.png
    - assets/images/3.0x/chs_logo_hsa.png

    - assets/images/ylz_message_logo.png
    - assets/images/2.0x/ylz_message_logo.png
    - assets/images/3.0x/ylz_message_logo.png

    - assets/images/ylz_home_find.png
    - assets/images/2.0x/ylz_home_find.png
    - assets/images/3.0x/ylz_home_find.png

    - assets/images/ylz_elec_code.png
    - assets/images/2.0x/ylz_elec_code.png
    - assets/images/3.0x/ylz_elec_code.png

    - assets/images/ylz_eye_open.png
    - assets/images/2.0x/ylz_eye_open.png
    - assets/images/3.0x/ylz_eye_open.png

    - assets/images/ylz_logo.png
    - assets/images/2.0x/ylz_logo.png
    - assets/images/3.0x/ylz_logo.png

    - assets/images/ylz_home_scan.png
    - assets/images/2.0x/ylz_home_scan.png
    - assets/images/3.0x/ylz_home_scan.png

    - assets/images/ylz_home_qrcode.png
    - assets/images/2.0x/ylz_home_qrcode.png
    - assets/images/3.0x/ylz_home_qrcode.png

    - assets/images/ylz_home_care.png
    - assets/images/2.0x/ylz_home_care.png
    - assets/images/3.0x/ylz_home_care.png

    - assets/images/ylz_blank_rectangle.png
    - assets/images/2.0x/ylz_blank_rectangle.png
    - assets/images/3.0x/ylz_blank_rectangle.png

    - assets/images/ylz_blank_circular.jpg
    - assets/images/2.0x/ylz_blank_circular.jpg

    - assets/images/ylz_elec_code_supporting.png
    - assets/images/2.0x/ylz_elec_code_supporting.png
    - assets/images/3.0x/ylz_elec_code_supporting.png

    - assets/images/ylz_elec_code_bg.png
    - assets/images/2.0x/ylz_elec_code_bg.png
    - assets/images/3.0x/ylz_elec_code_bg.png

    - assets/images/ylz_elec_code_deal_record.png
    - assets/images/2.0x/ylz_elec_code_deal_record.png
    - assets/images/3.0x/ylz_elec_code_deal_record.png

    - assets/images/ylz_elec_code_use_record.png
    - assets/images/2.0x/ylz_elec_code_use_record.png
    - assets/images/3.0x/ylz_elec_code_use_record.png

    - assets/images/ylz_elec_code_dot.png
    - assets/images/2.0x/ylz_elec_code_dot.png
    - assets/images/3.0x/ylz_elec_code_dot.png

    - assets/images/ylz_elec_code_fresh.png
    - assets/images/2.0x/ylz_elec_code_fresh.png
    - assets/images/3.0x/ylz_elec_code_fresh.png

    - assets/images/ylz_elec_code_small_logo.png
    - assets/images/2.0x/ylz_elec_code_small_logo.png
    - assets/images/3.0x/ylz_elec_code_small_logo.png

    - assets/images/ylz_black_back.png
    - assets/images/2.0x/ylz_black_back.png
    - assets/images/3.0x/ylz_black_back.png

    - assets/images/ylz_failure_image.png
    - assets/images/2.0x/ylz_failure_image.png
    - assets/images/3.0x/ylz_failure_image.png

    - assets/images/ylz_area_notice.png
    - assets/images/2.0x/ylz_area_notice.png
    - assets/images/3.0x/ylz_area_notice.png

    - assets/images/ylz_area_bg.png
    - assets/images/2.0x/ylz_area_bg.png
    - assets/images/3.0x/ylz_area_bg.png

    - assets/images/ylz_area_china.png
    - assets/images/2.0x/ylz_area_china.png
    - assets/images/3.0x/ylz_area_china.png

    - assets/images/ylz_area_location.png
    - assets/images/2.0x/ylz_area_location.png
    - assets/images/3.0x/ylz_area_location.png

    - assets/images/ylz_area_arrow.png
    - assets/images/2.0x/ylz_area_arrow.png
    - assets/images/3.0x/ylz_area_arrow.png

    - assets/images/ylz_mine_list_about.png
    - assets/images/2.0x/ylz_mine_list_about.png
    - assets/images/3.0x/ylz_mine_list_about.png

    - assets/images/ylz_mine_list_setting.png
    - assets/images/2.0x/ylz_mine_list_setting.png
    - assets/images/3.0x/ylz_mine_list_setting.png

    - assets/images/ylz_mine_list_info.png
    - assets/images/2.0x/ylz_mine_list_info.png
    - assets/images/3.0x/ylz_mine_list_info.png

    - assets/images/ylz_mine_list_notice.png
    - assets/images/2.0x/ylz_mine_list_notice.png
    - assets/images/3.0x/ylz_mine_list_notice.png

    - assets/images/ylz_mine_list_help.png
    - assets/images/2.0x/ylz_mine_list_help.png
    - assets/images/3.0x/ylz_mine_list_help.png

    - assets/images/ylz_mine_real_sign.png
    - assets/images/2.0x/ylz_mine_real_sign.png
    - assets/images/3.0x/ylz_mine_real_sign.png

    - assets/images/ylz_mine_male_avater.png
    - assets/images/2.0x/ylz_mine_male_avater.png
    - assets/images/3.0x/ylz_mine_male_avater.png

    - assets/images/ylz_mine_bg.png
    - assets/images/2.0x/ylz_mine_bg.png
    - assets/images/3.0x/ylz_mine_bg.png

    - assets/images/ylz_mine_bank_card.png
    - assets/images/2.0x/ylz_mine_bank_card.png
    - assets/images/3.0x/ylz_mine_bank_card.png

    - assets/images/ylz_mine_notice.png
    - assets/images/2.0x/ylz_mine_notice.png
    - assets/images/3.0x/ylz_mine_notice.png

    - assets/images/ylz_mine_scan.png
    - assets/images/2.0x/ylz_mine_scan.png
    - assets/images/3.0x/ylz_mine_scan.png

    - assets/images/ylz_mine_use_record.png
    - assets/images/2.0x/ylz_mine_use_record.png
    - assets/images/3.0x/ylz_mine_use_record.png

    - assets/images/ylz_mine_deal_record.png
    - assets/images/2.0x/ylz_mine_deal_record.png
    - assets/images/3.0x/ylz_mine_deal_record.png

    - assets/images/ylz_mine_baby_avater.png
    - assets/images/2.0x/ylz_mine_baby_avater.png
    - assets/images/3.0x/ylz_mine_baby_avater.png

    - assets/images/ylz_mine_circle_add_place.png
    - assets/images/2.0x/ylz_mine_circle_add_place.png
    - assets/images/3.0x/ylz_mine_circle_add_place.png

    - assets/images/ylz_mine_circle_add.png
    - assets/images/2.0x/ylz_mine_circle_add.png
    - assets/images/3.0x/ylz_mine_circle_add.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
